{
  "formatVersion": "1.1",
  "component": {
    "group": "com.antonkarpenko",
    "module": "ffmpeg-kit-full-gpl",
    "version": "2.1.0"
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ffmpeg-kit-full-gpl-2.1.0.aar",
          "url": "ffmpeg-kit-full-gpl-2.1.0.aar",
          "size": 11958948,
          "sha512": "f16720b9e63c0fe83643e1c61633ed7272ff8703721ba39d13a1de33c2622634ba571f27056c2642383610ef82500a1ac7b1bb13b53a617f9be9ae35c2a51e7a",
          "sha256": "637227b2c374ffa104fdae9dc956c109999a481eea563d6f385d75b17eb7a684",
          "sha1": "ec6684e6f9422b8a604e0cef3988f607c9e38c2f",
          "md5": "06105531e5e49151e4356cbca7746192"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ffmpeg-kit-full-gpl-2.1.0.aar",
          "url": "ffmpeg-kit-full-gpl-2.1.0.aar",
          "size": 11958948,
          "sha512": "f16720b9e63c0fe83643e1c61633ed7272ff8703721ba39d13a1de33c2622634ba571f27056c2642383610ef82500a1ac7b1bb13b53a617f9be9ae35c2a51e7a",
          "sha256": "637227b2c374ffa104fdae9dc956c109999a481eea563d6f385d75b17eb7a684",
          "sha1": "ec6684e6f9422b8a604e0cef3988f607c9e38c2f",
          "md5": "06105531e5e49151e4356cbca7746192"
        }
      ]
    }
  ]
}