{
  "formatVersion": "1.1",
  "component": {
    "group": "com.antonkarpenko",
    "module": "ffmpeg-kit-full-gpl",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ffmpeg-kit-full-gpl-2.1.0.aar",
          "url": "ffmpeg-kit-full-gpl-2.1.0.aar",
          "size": 12003000,
          "sha512": "a943caedeab8f223455d6ba81545757ab9c34a386c60bb838ba7e3a4ba2fe456e5f63f275d3699ca4a54dee333ae34264aeb2a2b67cad2e56f4d8df3510d714d",
          "sha256": "c9792a0e74065689f7b1f76546d8e90630e3a604228444d719c201aa7b84d22b",
          "sha1": "5cd8d5c6d56c3ac22fae8fae52f0db82dda32543",
          "md5": "628ee541b7df3c45efe1dc899fea138b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ffmpeg-kit-full-gpl-2.1.0.aar",
          "url": "ffmpeg-kit-full-gpl-2.1.0.aar",
          "size": 12003000,
          "sha512": "a943caedeab8f223455d6ba81545757ab9c34a386c60bb838ba7e3a4ba2fe456e5f63f275d3699ca4a54dee333ae34264aeb2a2b67cad2e56f4d8df3510d714d",
          "sha256": "c9792a0e74065689f7b1f76546d8e90630e3a604228444d719c201aa7b84d22b",
          "sha1": "5cd8d5c6d56c3ac22fae8fae52f0db82dda32543",
          "md5": "628ee541b7df3c45efe1dc899fea138b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ffmpeg-kit-full-gpl-2.1.0-sources.jar",
          "url": "ffmpeg-kit-full-gpl-2.1.0-sources.jar",
          "size": 47404,
          "sha512": "5f2ef3a4654c5b88926bfee5e4af66bec9c96a7332120c9bc0709ec184b4ccbdf6255774c5c25d8d8fab70eefd34597b2e32ee7b0518e9250101838726bd519f",
          "sha256": "ca9d170e02a39f7056f8b448460f85f4be4997bbfbed0a468ce599efe84cd5b2",
          "sha1": "2570797229e6c4c93fc674bf55d59dd0f3048d1c",
          "md5": "bcae43499a53a2e5d24ac8cd6a0d6e49"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ffmpeg-kit-full-gpl-2.1.0-javadoc.jar",
          "url": "ffmpeg-kit-full-gpl-2.1.0-javadoc.jar",
          "size": 416461,
          "sha512": "ea41a4b818170f424e482d85152f5f654dc9c8620bc5c29af417d958451a63a538779cfcad7c74ca99803577729b19a1cf0e241e2a12e23ea4d5d2d642035450",
          "sha256": "f327da9d2a4f4b659a9894298aa734426e141efe9fa37e3e9a0a0c571934e51b",
          "sha1": "ca01660d06eb744e94905b22a095844da12d362d",
          "md5": "514d9c1ba35c47b460382ec97436f44f"
        }
      ]
    }
  ]
}